/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg4.learn4_gui_ej_cronometro;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author Alex
 */
public class VentanaCronometro extends javax.swing.JFrame {

    /**
     * Creates new form VentanaCronometro
     */
    private Timer tiempo;
    private long startTime;
   private int centesimaSeg=0,Segundos=0,Minutos=0,horas=0; 
   

    public VentanaCronometro() {
        initComponents();
        jTextField1.setEditable(false);
        tiempo = new Timer(10, Accion);

    }

    // Crea una nueva implementación de la interfaz ActionListener.
    private ActionListener Accion = new ActionListener() {

        // Sobrescribe el método actionPerformed() para manejar eventos de acción.
        @Override
        public void actionPerformed(ActionEvent ae) {
            
            centesimaSeg++;
            if(centesimaSeg==100){
             Segundos++;
             centesimaSeg=0;            
            }
            if (Segundos==60){
            Minutos++;
            Segundos=0;
            }
            if (Minutos==60){
            horas++;
            Minutos=0;
            }
            actualizarEtiquetas();
        }
        
    };
    
    private void actualizarEtiquetas(){
    String texto= (horas<=9?"0":"")+horas+(Minutos<=9?"0":";")+":"+Minutos+(Segundos<=9?"0":"")+":"+Segundos+(centesimaSeg<=9?"0":"")+":"+centesimaSeg;
    jTextField1.setText(texto);
    
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        BIniciar = new javax.swing.JButton();
        BPauisar = new javax.swing.JButton();
        BReset = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 240));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BIniciar.setBackground(new java.awt.Color(238, 121, 224));
        BIniciar.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        BIniciar.setForeground(new java.awt.Color(51, 0, 204));
        BIniciar.setText("Iniciar");
        BIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BIniciarActionPerformed(evt);
            }
        });
        getContentPane().add(BIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, -1));

        BPauisar.setBackground(new java.awt.Color(238, 121, 224));
        BPauisar.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        BPauisar.setForeground(new java.awt.Color(51, 0, 204));
        BPauisar.setText("Pausar");
        BPauisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPauisarActionPerformed(evt);
            }
        });
        getContentPane().add(BPauisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, -1, -1));

        BReset.setBackground(new java.awt.Color(238, 121, 224));
        BReset.setFont(new java.awt.Font("Georgia", 1, 12)); // NOI18N
        BReset.setForeground(new java.awt.Color(51, 0, 204));
        BReset.setText("Reiniciar");
        BReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BResetActionPerformed(evt);
            }
        });
        getContentPane().add(BReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, -1, -1));

        jTextField1.setBackground(new java.awt.Color(204, 204, 204));
        jTextField1.setFont(new java.awt.Font("Engravers MT", 0, 14)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 200, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\Alex Games\\Documents\\NetBeansProjects\\4-Learn4_GUI_Ej_Cronometro\\src\\Imagenes\\Screenshot_1.jpg")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 80, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/CronometroBandera.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 225));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BIniciarActionPerformed
        tiempo.start();
    }//GEN-LAST:event_BIniciarActionPerformed

    private void BPauisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPauisarActionPerformed
        // TODO add your handling code here:
        tiempo.stop();
    }//GEN-LAST:event_BPauisarActionPerformed

    private void BResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BResetActionPerformed
        tiempo.stop();
        centesimaSeg=0;
        Segundos=0;
        Minutos=0;
        horas=0; 
         
        actualizarEtiquetas();
        
    }//GEN-LAST:event_BResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCronometro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCronometro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCronometro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCronometro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCronometro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BIniciar;
    private javax.swing.JButton BPauisar;
    private javax.swing.JButton BReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}

//import javax.swing.*;
//import java.awt.event.ActionEvent;
//import java.awt.event.ActionListener;
//import java.text.DecimalFormat;
//import java.text.NumberFormat;
//
//public class Cronometro extends JFrame {
//    private JTextField textField;
//    private Timer timer;
//    private long startTime;
//
//    public Cronometro() {
//        setTitle("Cronómetro");
//        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//        setSize(200, 100);
//        setLocationRelativeTo(null);
//
//        textField = new JTextField("0.000");
//        textField.setEditable(false);
//        add(textField);
//
//        timer = new Timer(10, new ActionListener() {
//            @Override
//            public void actionPerformed(ActionEvent e) {
//                long currentTime = System.currentTimeMillis();
//                double elapsedTime = (currentTime - startTime) / 1000.0; // segundos
//                NumberFormat formatter = new DecimalFormat("0.000");
//                textField.setText(formatter.format(elapsedTime));
//            }
//        });
//
//        JButton startButton = new JButton("Iniciar");
//        startButton.addActionListener(new ActionListener() {
//            @Override
//            public void actionPerformed(ActionEvent e) {
//                startTime = System.currentTimeMillis();
//                timer.start();
//            }
//        });
//
//        JButton stopButton = new JButton("Detener");
//        stopButton.addActionListener(new ActionListener() {
//            @Override
//            public void actionPerformed(ActionEvent e) {
//                timer.stop();
//            }
//        });
//
//        JButton resetButton = new JButton("Reiniciar");
//        resetButton.addActionListener(new ActionListener() {
//            @Override
//            public void actionPerformed(ActionEvent e) {
//                timer.stop();
//                textField.setText("0.000");
//            }
//        });
//
//        JPanel buttonPanel = new JPanel();
//        buttonPanel.add(startButton);
//        buttonPanel.add(stopButton);
//        buttonPanel.add(resetButton);
//        add(buttonPanel, "South");
//
//        pack();
//    }
//
//    public static void main(String[] args) {
//        SwingUtilities.invokeLater(new Runnable() {
//            @Override
//            public void run() {
//                new Cronometro().setVisible(true);
//            }
//        });
//    }
//}
